{% set version = "1.6.0" %}

package:
  name: backports.functools_lru_cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-{{ version }}.tar.gz
  sha256: 6bf7b39947b43e7835d889a2ce6ed4e0ddbed10aee17540c5fe56a0cd6a444ce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - backports

  run:
    - python
    - setuptools
    - backports

test:
  imports:
    - backports.functools_lru_cache

about:
  home: https://github.com/jaraco/backports.functools_lru_cache
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Backport of functools.lru_cache from Python 3.3 as published at ActiveState.'
  doc_url: https://pypi.python.org/pypi/backports.functools_lru_cache
  dev_url: https://github.com/jaraco/backports.functools_lru_cache

extra:
  recipe-maintainers:
    - mariusvniekerk
    - stuertz
