travis:
  secure:
    BINSTAR_TOKEN: hc47qJGbWlVydnMs4Dd5ToiEVDU5lMElqZfRsrUDMZwNZANWtQvjhWdb9j4CMvY5/GL461ux9EPtzs61amYp9sVlnpNboqTOe5XSy3PplkwCBFEAx1ffimf2tc1ahdDnqGah0z62f7aE305EbE+DOH71WDG2kTO1a2NbJuvJlfk3vRzAjNGEeegFM4IvQD5yCO4mvBErz5CDBGQAStRS99rTXvX2jLPnPyRPulJocc5t/nQqb3GvO94ZqnvYFCJpoDCr2k5iFoSayYwuMiMhUvzIAAAsYXU4JGtetHkbJqE13OH9ugk6Y6Nx/WbnQ/vQGPRfrtvfIKB/EqO85E4PLOUW80dG4HnxzJ/w6gLHASO1zm1OfKBXfCsLxU1uBmX4HCJKcHz+Yx0HdkQj+OsBEwxvxYL2KNjvuWMZeXhs2/qtt0hqy92Kc+42cCq0gL+F9J6/FrssYqlZ+ZSuXAWWRn0IZapqlSavTVX3W5D6dXwDgc3fmtyvkIkj8xUArFERlXjvXCIjjGGoa0ClC5GMM39l2kICqz4OVjCUjyU4dkPAzvQWeuYH3zjIlpd0DkXFf2R79UUkS5TYzjTfoWPb65CooSrcoCm0WQh8dCGbVBZstdJvThpIvRwkTp2RQQHT9TRag4rz/wzG1lY50wUTDGFzaUZPSf0ypGvLNb2NV84=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
