travis:
  secure:
    BINSTAR_TOKEN: a5xmbuyhkDTsh/jfQ9llMK1aH7EWHf5voWJb7UmeGQuW++UjzIiPlLlHaj66f6P5YnWNN+JFQqxr75UqLN/LpgjkTSCgHWl7diytPslB+n09OAfTMsZHYqWgYv1PfEBGwiFcQlL9VoULB1rQZiKjN1JrTlDXbWn4xRcepM5N9PFtt6MV4h7iE7LuEGDxFJ7igxPNuCDoyPKvRKPinQdx/k9bzvxETPMN+ayl/41liaHC0jc8ljowxeY7wczGW8B/hsfigrxZxoUDisJDeTj4abtIhxftn7AnZ3zZphYxnYGj6BijR82YcA2wQlvRuJwNP/VQoQgtW+6kuDHw92NMpHnNWl/IJrsS3YLlizrQPRUsBbC8+LVWqKvWjzRbpJnFJIV1vSv3zkh16fvU7oHZ59mHOhorgnBvYY9fI62GTwPP5Eayq1hKeNUbK4yckCQnBOSBTulj6Tdwoj4uED3wIwuMjzWluDKsjVcqPRKjNtZHs7h378EYO/yl/Rjn8utMN89vLHKItGi/hrZMWgJQYQzJ43eOZ9mmeEVCiXfDN3wN2c54/GZ61jzNpZcn4ncmEQAVylUl2io5fOwa915m/TY3hrIJVVUkTvm3EH6c7a3xLPrpAGdVBh2zMmtgb0k74EL7lzKAT4wzCf8fOl5LYMLxmh8achwpPm3dhLpKR0o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
